
{'date': 'Wed Sep 25 2019 11:44:14.429 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 3
  """
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Sep 25 2019 11:45:00.423 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 2
  __author__ = "Claudia L R Motta (claudiam@nce.ufrj.br)"
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Sep 25 2019 12:11:01.377 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  ."""Inicia a construção do Jogo"""
   ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Sep 25 2019 12:11:18.36 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 22
  self.cena_do_templo.vai()       
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Oct 02 2019 11:21:10.374 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 63
  self.cena_do_templo.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Oct 02 2019 11:21:21.865 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 70
  print(help(PedrasPreciosas.aumenta)
       ^
SyntaxError: Unbalanced bracket (
'''},
{'date': 'Wed Oct 02 2019 11:21:32.186 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 70
  print(help(PedrasPreciosas.aumenta)
       ^
SyntaxError: Unbalanced bracket (
'''},
{'date': 'Wed Oct 02 2019 11:22:50.401 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 71
  print(help(PedrasPreciosas.aumenta)
       ^
SyntaxError: Unbalanced bracket (
'''},
{'date': 'Wed Oct 09 2019 11:46:19.563 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 112
    jogo = JogoTesouroInca()
  module <module> line 101
    self.tumba = Tumba(self.acampamento, self.eu)
  module <module> line 74
    self.tumba = [Tesouros(pedras+1, acampamento, eu) for pedras in range(4)]
  module <module> line 66
    self.pedras = PedrasPreciosas(quantas_pedras=self.tesouro)
  module <module> line 44
    self.pedras_especificas = [Elemento(
  module elemento.main line 40
    self.scorer = dict(ponto=1, valor=cena.nome, carta=tit or img, casa=self.xy, move=None)
AttributeError: 'PedrasPreciosas' object has no attribute 'nome'
'''},
{'date': 'Wed Oct 09 2019 11:50:48.857 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 114
    jogo = JogoTesouroInca()
  module <module> line 103
    self.tumba = Tumba(self.acampamento, self.eu)
  module <module> line 76
    self.tumba = [Tesouros(pedras+1, acampamento, eu) for pedras in range(4)]
  module <module> line 68
    self.pedras = PedrasPreciosas(quantas_pedras=self.tesouro)
  module <module> line 44
    self.pedras_especificas = [Elemento(
  module elemento.main line 40
    self.scorer = dict(ponto=1, valor=cena.nome, carta=tit or img, casa=self.xy, move=None)
AttributeError: 'PedrasPreciosas' object has no attribute 'nome'
'''},
{'date': 'Wed Oct 09 2019 11:58:26.884 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 117
    jogo = JogoTesouroInca()
  module <module> line 106
    self.tumba = Tumba(self.acampamento, self.eu)
  module <module> line 79
    self.tumba = [Tesouros(pedras+1, acampamento, eu) for pedras in range(4)]
  module <module> line 71
    self.pedras = PedrasPreciosas(quantas_pedras=self.tesouro)
  module <module> line 44
    self.pedras_especificas = [Elemento(
  module elemento.main line 40
    self.scorer = dict(ponto=1, valor=cena.nome, carta=tit or img, casa=self.xy, move=None)
AttributeError: 'PedrasPreciosas' object has no attribute 'nome'
'''},